import { Inter, Roboto } from "next/font/google";
import "./globals.css";

// Configuration for Inter
const inter = Inter({
  subsets: ["latin"]
});

// Configuration for Roboto
const roboto400 = Roboto({
  subsets: ["latin"],
  weight: '500'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto400.className}`}>
        {children}
      </body>
    </html>
  );
}